version: "3.3"
services:
  ssl:
    image: vishnunair/docker-mkcert
    volumes:
      - wortixcerts:/root/.local/share/mkcert
  nginx:
    image: "nginx:1.21"
    volumes:
      - ./../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wortixcerts:/root/certs
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    networks:
      - wortixnet
  php:
    build: php
    ports:
      - "9090:9090"
    volumes:
      - ./../:/var/www/html
    networks:
      - wortixnet
  mysql:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - wortixmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wortixnet
networks:
  wortixnet:
volumes:
  wortixmysql:
  wortixcerts:
